---
title: "0413選取元素"
author: "SamueiTai"
date: "2020/4/12"
output: html_document
---


```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```

```{r}
vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```
```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap
length(tainanSportsMap)
```

```{r}
tainanSportsMap[[3]]
tainanSportsMap[[1076]]
```


```{r}
listExample$`學期` # 特殊命名依然要用反頓點呼叫
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
str(newTaipeiCityVaccine)
```

```{r}
length(newTaipeiCityVaccine)
```

```{r}
newTaipeiCityVaccine[["success"]]
```
```{r}
newTaipeiCityVaccine[[1]]
```

```{r}
newTaipeiCityVaccine$success
```

```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c("學期")]
listExample[c("student","學期")]
```
```{r}
str(tainanSportsMap, max.level = 1)
str(tainanSportsMap[c(3, 456, 8)], max.level = 1)
```

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

```{r}
taipeiNightMarkets[c(3,5,7)]
```


```{r}
vectorExample
vectorExample[c(T,T,F)] # 要，要，不要
```

```{r}
str(listExample)
```

```{r}
str(listExample[c(T,F)])
```

```{r}
names(taipeiNightMarkets)
```

```{r}
str(taipeiNightMarkets[c(T,F,F,F,T,F,F,F,F,T,F,F,F,T)], max.level = 1)
```
```{r}
selectedMarket <- rep(F,14)
selectedMarket[c(1,5,10,14)] <- T
```


```{r}
str(listExample)
```

```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]
```

```{r}
numVector <- c(2,3,6,-1,4,2,6)
select1 <- numVector[c(1,4)]; select1
select2 <- select1[[1]]; select2

# 相當於
numVector[c(1,4)][[1]]
```


```{r}
select1 <- numVector[c(T,T,F,T,F,F,T)]; select1
select2 <- select1[c(1,4)]; select2

# 相當於
numVector[c(T,T,F,T,F,F,T)][c(1,4)]
```
```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")

econOnly <- majors[c(T,T,F,F,T)]
names[econOnly]
gender[econOnly]

econFemaleOnly <- econOnly[c(T,T,F)]
names[econFemaleOnly]
```


```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")

econOnly <- c(1,2,5)
names[econOnly]
gender[econOnly]

econFemaleOnly <- econOnly[c(T,T,F)]
names[econFemaleOnly]
```


```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")

econOnly <- majors[c(1,2,5)]
names[econOnly]
gender[econOnly]
econFemaleOnly <-gender[econOnly][c(T,T,F)]
names[econOnly][econFemaleOnly]
```


